name: Update and Test Config

on:
  push:
    branches:
      - main
  schedule:
    # 每天执行一次 (UTC时间)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 步骤1: 检出你的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 步骤3: 安装依赖项
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 步骤4: 运行 update_config.py 生成 config.json
      - name: Run update_config.py to generate config.json
        run: python update_config.py

      # 步骤5: 运行 test_api_availability.py 测试新配置 (核心改动)
      # 添加 --yes 参数来自动确认所有操作
      - name: Run test_api_availability.py to test the new config
        run: python test_api_availability.py --yes

      # 步骤6: 提交并推送生成的 config.json 文件
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update and test config.json"
          file_pattern: "config.json"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
